### ISSUE TITLE
spacing in schema output

### ISSUE THREAD

**Issue by Liopia** [alwaysblank/schemer#1]
lack os space between output spans (noticed in PostalAddress build output) creates issues in formatting and prevents an easy copy-paste experience for a user.

**Comment by alwaysblank** [comment]
IIRC my intent was to make the output string as agnostic as possible w/r/t to formatting, i.e. it just dumps out spans and you add spacing, etc w/ CSS. I'd be open to suggestions for ways to improve the experience while maintaining a flexible experience. Some possible ideas:

- A toggle that puts something like `<span>&nbsp;</span>` between each item, which can then be added/removed as needed. Problem is that this adds a lot of more or less unnecessary HTML.
- Change elements to default to a block-level wrapper (i.e. `div` rather than `span`) which automatically moves them to separate lines for better visual separation, but can then be converted to inline-level element through CSS if desired. Problem (minor) is that semantically these aren't block-level elements, so we're using a tag for its presentation rather than its meaning, which I'm not jazzed about.
- Expose some kind of filter for each node during the render process that allows you to modify them on the fly. This would allow for a great deal of flexibility, but would significantly increase complexity (esp. for a simple task like "add a space please").
